name: Create FHIR code system

on:
  push:

jobs:
  generate:
    name: Create FHIR Code System
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Remove FHIR code system from Git
        run: git rm --ignore-unmatch rel-fhir.json

      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Download FHIR-OWL
        uses: wei/wget@v1
        with:
          args: -O fhirowl.jar https://github.com/aehrc/fhir-owl/releases/download/v1.1/fhir-owl-v1.1.jar

      - name: Run transformation
        run: java -jar fhirowl.jar -i src/main/resources/rel.owl -o rel-fhir.json -r jfact -useFhirExtension -dateRegex "(?<year>\\d{4})-(?<month>\\d{2})-(?<day>\\d{2})" -n FamilyHistoryRelationsOntology -t "Family History Relations Ontology"

      - name: Add new FHIR code system from Git
        run: git add rel-fhir.json

      - name: Set up Git config
        run: |
          git config --local user.email "358260+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"

      - name: Commit FHIR code system
        run: git commit -m "Created FHIR code system"

      - name: Push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}