name: Test

on:
  push:

jobs:
  test:
    name: Build and test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Run the test goal with Maven
        run: mvn test --batch-mode --fail-at-end
        timeout-minutes: 30